### ISSUE TITLE
Question on permission

### ISSUE THREAD

**Issue by IzzySoft** [Kaiserdragon2/CallForwarding#10]
For the latest release, the scanners at IoD reported:

```
! repo/de.kaiserdragon.callforwardingstatus_6.apk declares sensitive permission(s): android.permission.READ_PHONE_STATE
! repo/de.kaiserdragon.callforwardingstatus_6.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

The `READ_PHONE_STATE` permission was not there before. Could you please clarify what it is now needed for? As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided by a little adjustment to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by Kaiserdragon2** [comment]
I don't know why the permission thing just came up. It is there form the beginning ([Manifest v1.3](https://github.com/Kaiserdragon2/CallForwarding/blob/v1.3/app/src/main/AndroidManifest.xml)) and it is needed to read the call forwarding status indicator with this the widget displays the current call forwarding status and decides what to do when pressing the toggle call forwarding button.

**Comment by IzzySoft** [comment]
OK, sounds reasonable. I'll put it to the green list then with that description:

```yaml
android.permission.READ_PHONE_STATE: needed to read the call forwarding status indicator
```

And thanks for taking care about that blob! Should be gone then with the next release – so all done here and we can close this issue :partying_face:
