### ISSUE TITLE
Call forward toggle fail

### ISSUE THREAD

**Issue by Sponge4741** [Kaiserdragon2/CallForwarding#2]
After entering a number and tapping save (and receive a toast confirming save) I tap "toggle call forwarding" and it gives toast saying "-1", it doesn't toggle on. Tried with the widget, same result. 
On Samsung S7 without GSM.

**Comment by Kaiserdragon2** [comment]
Could you try if call forwarding works by entering \*21\*NUMBER# into your standard phone app to deactivate #21#.

**Comment by Kaiserdragon2** [comment]
Something else to note is that it could be that no Radiobutton was selected in the app, because at the moment the app doesn't not autoselect the first entry.
